baseURL = 'https://christianegas2112.github.io/portafolio/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "tales" 

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contact"
	title = "Contact"
	url = "/contact/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0
