baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-es"
title: "Christian Pesantes"
theme: tales

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: Sisgit
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"


  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  #navbar:
    #align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    #brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    #disableSearch: false
    # searchPlaceholder: "Search"
    #menus:
      #disableAbout: false
      #disableExperience: false
      #disableEducation: false
      #disableProjects: false
      #disableAchievements: false
      #disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Protafolio"
    title: "Christian Valentin Pesantes Egas"
    subtitle: "Tecnologo en desarrollo de software"
    content: "la contruccion de una app nativa desde 0 usando  la documentacion de flutter para asi crear tanto el diseño para que escale dependiendo a la pantalla que se visualize, creando la respuesta de notificaciones, usando API de otras pagina para mantener actualizado el contenido, manejo de base de datos, creando diferentes  layouts dentros de las paginas web o app movil, creacion de inventarios con o sin interfaz grafica, implementacion de sistemas open source y creacion de banner logos tarjeta de presentacion."
    content1: "En mis tiempos libres me gusta investigar como mejorar el rendimiento de maquinas de bajos recursos asi sacarle todo el rendimiento que puede dar. [Cv.pdf](https://duckduckgo.com)"
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    #button:
      #enable: true
      #name: "Resume"
      #url: "#"
      #download: true
      #newPage: false
    #socialLinks:
      #fontAwesomeIcons:
        #- icon: fab fa-github
          #url: https://example.com
        #- icon: fab fa-twitter
          #url: https://example.com
      #customIcons:
        #- icon: /fav.png
          #url: "https://example.com"

  # About
  #about:
    #enable: true
    #title: "About Me"
    #image: "/images/me.png"
    #content: |-
      #I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

      #I am currently working on a project that will be used to help people find the best way to get around the city.
    #skills:
      #enable: true
      #title: "Here are a few technologies I've been working with recently:"
      #items:
        #- "HTML"
        #- "CSS"
        #- "JavaScript"
        #- "React"
        #- "Node"
        #- "Express"

  # Experience
  experience:
    enable: true
    title: "Experiencia"
    items:
      - job: "Desarrollo y diseño web"
        company: "LIDE"
        companyUrl: ""
        date: "Mar 2022 - 2022"
        featuredLink:
          enable: true
          name: "ver proyecto"
          url: ""
          info:
          enable: true
          content: Diseño web del lide.
        content: "Colaborador dentro del desarrollo de la pagina del lide, propuesta de diseño, en donde se trabajara todo de una plantilla para luego personalizarla en la que fui participe para aplicar algunas parte de esta pagina del LIDE. "

      - job: "Administrador de inventario"
        company: "Almacen Figeroa"
        companyUrl: ""
        date: "Sep 2019 - Dec 2019"
        featuredLink:
          enable: true
          url: ""
        info:
          enable: true
          content: trabaje durante 4 meses.
        content: "Se manejo el inventario que los item o mercaderia en stock del piso que estaba encargado para registrar que unides estan disponibles y cuanto hay de cada unidad."

      - job: "Tecnico"
        company: "Personal"
        companyUrl: ""
        date: "Ago 2021 - Actualidad"
        info:
          enable: true
          content: optimizaciones y intalaciones de windows.
        featuredLink:
          enable: true
          url: ""
        content: |
            Me encargado de mejorar el rendimiento del windows de maquinas de poco recurso muy parte actualizar los drives, intalacion de sistema y quitar algunos servio o recomendar el hardware y su instalación.

     
  # Education
  education:
    enable: true
    title: "Educación"
    index: false
    items:
      - title: "Desarrollador de software"
        school:
          name: "Tecnologico Argos"
          url: ""
        date: "2021 - actualidad"
        GPA: "4.0/5.0"
        content: |-
         propuesta de proyectos, desarrollo de programas tales como inventario, una interfaz grafica de un simulador de cajero automatico, las fases de la contruccion del desarrollo de estas tecnologias, manejo de redes y telecomunicaciones, manejo diferentes herramientas CASE, open source y base de datos.

      - title: "Graduado en bachillerato general"
        school:
          name: "Unidad Educativa GAUSS"
          url: ""
        date: "2015 - 2019"
        GPA: "4.0/5.0"
        content: |-
          Graduado en la unidad educativa gauss en donde participe en un mini proyecto en un diseño de comic en la parte de emprendimiento en la que se llamos esta revista starnick, mejores calificaciones en la parte de matematicas, fisica y quimica que todo lo relacionado con calculo tengo mejor agilidad, participe en concursos de matematicas.
        featuredLink:
          enable: false
          name: ""
          url: ""
    

  # Achievements
  achievements:
    enable: true
    title: "Cursos"
    items:
      - title: Flutter en Udemy (2020)
        content: Diferentes tipos de aplicacion nativas en la que se ve a diario.
        url: https://www.udemy.com/

      - title: R básico en Datacamp (2022) 
        content: Manejo de datos analiticos asi con mayor facilidad que otros lenguajes
        url: https://www.datacamp.com/

      - title: R intermedio en finanzas en Datacamp (2022)
        content: Manejo en la parte de finanzas para la realizacion de calculos y aplicando dentro del codigo calculos de la area de finanza.
        url: https://www.datacamp.com/

      - title:	Script Bash en Datacamp (2022)
        content: los uso de los comandos basico en el git bash tambien como aplicar o crear los script.
        url: https://www.datacamp.com/

      - title:	Git/GitHub en Datacamp (2022)
        content: aprender el uso de githud hacer los controles versiones
        url: https://www.datacamp.com/

 # projects
  projects:
    enable: true
    title: "Proyectos"
    items:
      - title: Aplicación de películas en Flutter (2020)
        content: un modelo de aplicacion nativa de Android en donde permite ver el resumen de las peliculas tanto recientes, elaborado con el lenguaje dart con la documentacion de flutter.
        image: /images/pelicula_app.PNG
        featured:
          name: ver 
          link: https://github.com/ChristianEgas2112/demo_practica.git
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/ChristianEgas2112/demo_practica.git

      - title: Creación de un minijuego en HTTP (2019)
        content: un mini video juego elaborado tan solo con css3 y html5 de una navecita esquivando meteoritos.
        image: /images/mini_juego.PNG
        featured:
          name: ver
          link: https://github.com/ChristianEgas2112/Primer-proyecto.git
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/ChristianEgas2112/Primer-proyecto.git

      - title: Creación de un comic llamado “starnick” (2017) 
        content: se hice un mini proyecto para la creacion de un comic llamadado starnick, con la animacion a mano asi sacando solo el primer capitulo.
        image: /images/starnick_comic.PNG
        featured:
          name: ver
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  #contact:
    #enable: true
    # title: "Custom Name"
    #content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    #email: gurusabarisha@gmail.com
    #btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  #footer:
    #recentPosts:
      #path: "blogs"
      #count: 3
      #title: Recent Posts
      #enable: true
      #disableFeaturedImage: false
    #socialNetworks:
      #github: https://github.com
      #linkedin: https://linkedin.com
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com

  # List pages like blogs and posts
  #listPages:
    #disableFeaturedImage: false

  # Single pages like blog and post
  #singlePages:
    #readTime:
      #enable: true
      #content: "min read"
    #scrollprogress:
      #enable: true

  # For translations
  #terms:
    #read: "Read"
    #toc: "Table Of Contents"
    #copyright: "All rights reserved"
    #pageNotFound: "Page not found"
    #emailText: "Check out this site"

  #datesFormat:
    #article: "Jan 2, 2006"
    #articleList: "Jan 2, 2006"
    #articleRecent: "Jan 2, 2006"
